/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RandomRouteImport } from './routes/random'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthHistoryRouteImport } from './routes/_auth/history'
import { Route as AuthListRouteImport } from './routes/_auth/list'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AnimeIndexRouteImport } from './routes/anime/index'
import { Route as AnimeIdRouteImport } from './routes/anime/$id'
import { Route as ApiImgRouteImport } from './routes/api/img'
import { Route as MangaIndexRouteImport } from './routes/manga/index'
import { Route as MangaIdRouteImport } from './routes/manga/$id'
import { Route as ApiAvatarIdRouteImport } from './routes/api/avatar/$id'
import { Route as ApiAuthGoogleIndexRouteImport } from './routes/api/auth/google/index'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHistoryRoute = AuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListRoute = AuthListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImgRoute = ApiImgRouteImport.update({
  id: '/api/img',
  path: '/api/img',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIndexRoute = MangaIndexRouteImport.update({
  id: '/manga/',
  path: '/manga/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarIdRoute = ApiAvatarIdRouteImport.update({
  id: '/api/avatar/$id',
  path: '/api/avatar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleIndexRoute = ApiAuthGoogleIndexRouteImport.update({
  id: '/api/auth/google/',
  path: '/api/auth/google/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/history': typeof AuthHistoryRoute
  '/list': typeof AuthListRoute
  '/profile': typeof AuthProfileRoute
  '/anime/$id': typeof AnimeIdRoute
  '/api/img': typeof ApiImgRoute
  '/manga/$id': typeof MangaIdRoute
  '/anime/': typeof AnimeIndexRoute
  '/manga/': typeof MangaIndexRoute
  '/api/avatar/$id': typeof ApiAvatarIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/history': typeof AuthHistoryRoute
  '/list': typeof AuthListRoute
  '/profile': typeof AuthProfileRoute
  '/anime/$id': typeof AnimeIdRoute
  '/api/img': typeof ApiImgRoute
  '/manga/$id': typeof MangaIdRoute
  '/anime': typeof AnimeIndexRoute
  '/manga': typeof MangaIndexRoute
  '/api/avatar/$id': typeof ApiAvatarIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google': typeof ApiAuthGoogleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_auth/history': typeof AuthHistoryRoute
  '/_auth/list': typeof AuthListRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/anime/$id': typeof AnimeIdRoute
  '/api/img': typeof ApiImgRoute
  '/manga/$id': typeof MangaIdRoute
  '/anime/': typeof AnimeIndexRoute
  '/manga/': typeof MangaIndexRoute
  '/api/avatar/$id': typeof ApiAvatarIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/': typeof ApiAuthGoogleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/random'
    | '/reset-password'
    | '/schedule'
    | '/search'
    | '/signup'
    | '/verify-email'
    | '/history'
    | '/list'
    | '/profile'
    | '/anime/$id'
    | '/api/img'
    | '/manga/$id'
    | '/anime/'
    | '/manga/'
    | '/api/avatar/$id'
    | '/api/auth/google/callback'
    | '/api/auth/google/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/random'
    | '/reset-password'
    | '/schedule'
    | '/search'
    | '/signup'
    | '/verify-email'
    | '/history'
    | '/list'
    | '/profile'
    | '/anime/$id'
    | '/api/img'
    | '/manga/$id'
    | '/anime'
    | '/manga'
    | '/api/avatar/$id'
    | '/api/auth/google/callback'
    | '/api/auth/google'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/login'
    | '/random'
    | '/reset-password'
    | '/schedule'
    | '/search'
    | '/signup'
    | '/verify-email'
    | '/_auth/history'
    | '/_auth/list'
    | '/_auth/profile'
    | '/anime/$id'
    | '/api/img'
    | '/manga/$id'
    | '/anime/'
    | '/manga/'
    | '/api/avatar/$id'
    | '/api/auth/google/callback'
    | '/api/auth/google/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RandomRoute: typeof RandomRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AnimeIdRoute: typeof AnimeIdRoute
  ApiImgRoute: typeof ApiImgRoute
  MangaIdRoute: typeof MangaIdRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  MangaIndexRoute: typeof MangaIndexRoute
  ApiAvatarIdRoute: typeof ApiAvatarIdRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleIndexRoute: typeof ApiAuthGoogleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/history': {
      id: '/_auth/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/list': {
      id: '/_auth/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof AuthListRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/img': {
      id: '/api/img'
      path: '/api/img'
      fullPath: '/api/img'
      preLoaderRoute: typeof ApiImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/': {
      id: '/manga/'
      path: '/manga'
      fullPath: '/manga/'
      preLoaderRoute: typeof MangaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar/$id': {
      id: '/api/avatar/$id'
      path: '/api/avatar/$id'
      fullPath: '/api/avatar/$id'
      preLoaderRoute: typeof ApiAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/': {
      id: '/api/auth/google/'
      path: '/api/auth/google'
      fullPath: '/api/auth/google/'
      preLoaderRoute: typeof ApiAuthGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthHistoryRoute: typeof AuthHistoryRoute
  AuthListRoute: typeof AuthListRoute
  AuthProfileRoute: typeof AuthProfileRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHistoryRoute: AuthHistoryRoute,
  AuthListRoute: AuthListRoute,
  AuthProfileRoute: AuthProfileRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RandomRoute: RandomRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AnimeIdRoute: AnimeIdRoute,
  ApiImgRoute: ApiImgRoute,
  MangaIdRoute: MangaIdRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  MangaIndexRoute: MangaIndexRoute,
  ApiAvatarIdRoute: ApiAvatarIdRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleIndexRoute: ApiAuthGoogleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
